bootstrap.servers=kafka-4-mirror:9092,kafka-5-mirror:9092,kafka-6-mirror:9092
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.truststore.location=/etc/ksqldb/client.truststore.jks
ssl.truststore.password=kafka-secret
ssl.endpoint.identification.algorithm=