import uuid
from typing import Final, TypeAlias

CategoryName: TypeAlias = str
Tags: TypeAlias = list[str]


CATEGORIES: Final[dict[CategoryName, Tags]] = {
    "electronics": ["gadgets", "mobile", "wireless", "battery", "portable", "audio"],
    "clothing": ["mens", "womens", "casual", "formal", "seasonal", "apparel"],
    "footwear": ["sneakers", "boots", "sandals", "casual", "sport", "leather"],
    "books": ["fiction", "nonfiction", "education", "bestseller", "paperback"],
    "toys": ["puzzles", "dolls", "building", "kids", "educational"],
    "sports": ["fitness", "outdoor", "equipment", "training", "apparel"],
    "automotive": ["accessories", "parts", "maintenance", "tools", "electronics"],
    "beauty": ["skincare", "makeup", "fragrance", "organic", "tools"],
    "home": ["decor", "kitchen", "linen", "storage", "furniture"],
    "groceries": ["organic", "snacks", "beverages", "pantry", "fresh"],
    "health": ["vitamins", "personalcare", "supplements", "wellness", "medical"],
    "jewelry": ["rings", "necklaces", "bracelets", "gold", "silver"],
    "baby": ["strollers", "feeding", "toys", "safety", "clothing"],
    "office": ["stationery", "furniture", "supplies", "electronics", "storage"],
    "appliances": ["kitchen", "laundry", "small", "energy", "portable"],
    "furniture": ["livingroom", "bedroom", "outdoor", "wood", "sofa"],
    "outdoor": ["camping", "gardening", "gear", "hiking", "portable"],
    "pets": ["food", "toys", "accessories", "grooming", "health"],
    "tools": ["handtools", "powertools", "hardware", "maintenance", "safety"],
    "crafts": ["arts", "sewing", "supplies", "hobby", "diy"],
    "games": ["boardgames", "videogames", "strategy", "family", "multiplayer"],
    "music": ["instruments", "audio", "records", "accessories", "streaming"],
    "garden": ["plants", "tools", "soil", "outdoor", "decor"],
    "kitchen": ["cookware", "utensils", "appliances", "storage", "gadgets"],
    "bedding": ["sheets", "pillows", "duvets", "linen", "comfort"],
    "accessories": ["bags", "belts", "hats", "scarves", "jewelry"],
    "apparel": ["tops", "bottoms", "outerwear", "seasonal", "casual"],
    "fitness": ["equipment", "training", "apparel", "nutrition", "wearables"],
    "technology": ["smart", "gadgets", "ai", "connectivity", "wearables"],
    "stationery": ["pens", "notebooks", "office", "art", "supplies"],
    "weapons": ["prohibited", "forbidden", "restricted", "dangerous", "illegal"],
    "drugs": ["prohibited", "controlled", "illegal", "prescription", "substances"],
    "counterfeit": ["prohibited", "fake", "unauthorized", "imitation", "fraudulent"],
    "stolen": ["prohibited", "recovered", "missing", "reported", "illegal"],
}

FORBIDDEN_CATEGORIES: Final[set[str]] = {"weapons", "drugs", "counterfeit", "stolen"}

CATEGORY_NAMES: Final[list[str]] = list(CATEGORIES.keys())
STORE_UUIDS: Final[list[str]] = [str(uuid.uuid4()) for i in range(100)]


PRODUCT_NAMES: Final[list[str]] = [
    "Apple iPhone 15 Pro",
    "Samsung Galaxy S24 Ultra",
    "Google Pixel 8 Pro",
    "Apple MacBook Pro 14",
    "Dell XPS 15",
    "Lenovo ThinkPad X1 Carbon",
    "Sony WH-1000XM5 Headphones",
    "Bose QuietComfort 45",
    "Apple AirPods Pro (2nd Gen)",
    "Samsung QLED 65 TV",
    "LG OLED C3 55",
    "Sony A7 IV Mirrorless Camera",
    "Canon EOS R6",
    "Nintendo Switch OLED",
    "PlayStation 5 Console",
    "Xbox Series X",
    "Samsung 990 PRO 2TB SSD",
    "Seagate Barracuda 4TB HDD",
    "Logitech MX Master 3S Mouse",
    "Razer BlackWidow Mechanical Keyboard",
    'ASUS ROG 27" Gaming Monitor',
    "Netgear Nighthawk WiFi 6 Router",
    "DJI Mini 4 Drone",
    "GoPro HERO12 Action Camera",
    "Fitbit Charge 6",
    "Apple Watch Series 9",
    "Dyson V15 Detect Vacuum",
    "Philips Airfryer XXL",
    "Breville Barista Express Espresso Machine",
    "Xiaomi Mi Electric Scooter M365",
    # NOTE: banned products
    "gun",
    "pistol",
    "rifle",
    "fake_watch",
    "stolen_phone",
    "illegal_drugs",
    "1984 the book",
]


BRANDS: Final[list[str]] = [
    # Technology & Electronics
    "Apple",
    "Samsung",
    "Sony",
    "Microsoft",
    "Dell",
    "HP",
    "Lenovo",
    "ASUS",
    "Acer",
    "LG",
    "Panasonic",
    "Philips",
    "Canon",
    "Nikon",
    "Bose",
    "JBL",
    "Intel",
    "AMD",
    "NVIDIA",
    "Xiaomi",
    "Huawei",
    "OnePlus",
    "Oppo",
    "Vivo",
    "Motorola",
    "Nokia",
    "BlackBerry",
    "HTC",
    "Google",
    "Amazon",
    "Toshiba",
    "Fujitsu",
    "Sharp",
    "Hitachi",
    "Epson",
    "Brother",
    "Logitech",
    "Razer",
    "Corsair",
    "SteelSeries",
    # Fashion & Apparel
    "Nike",
    "Adidas",
    "Puma",
    "Reebok",
    "Under Armour",
    "Zara",
    "H&M",
    "Gucci",
    "Prada",
    "Louis Vuitton",
    "Chanel",
    "Versace",
    "Ralph Lauren",
    "Tommy Hilfiger",
    "Calvin Klein",
    "Levi's",
    "Gap",
    "Uniqlo",
    "Champion",
    "Lacoste",
    "Burberry",
    "Armani",
    "Hugo Boss",
    "Diesel",
    "Balenciaga",
    "Givenchy",
    "Valentino",
    "Fendi",
    "Hermès",
    "Dolce & Gabbana",
    "Michael Kors",
    "Coach",
    "Kate Spade",
    "Tory Burch",
    "Marc Jacobs",
    "Alexander McQueen",
    "Bottega Veneta",
    "Moncler",
    "Stone Island",
    "Off-White",
    # Automotive
    "Toyota",
    "Ford",
    "BMW",
    "Mercedes-Benz",
    "Volkswagen",
    "Honda",
    "Tesla",
    "Audi",
    "Porsche",
    "Ferrari",
    "Chevrolet",
    "Nissan",
    "Hyundai",
    "Kia",
    "Mazda",
    "Subaru",
    "Jeep",
    "Volvo",
    "Jaguar",
    "Land Rover",
    "Lamborghini",
    "Bentley",
    "Rolls-Royce",
    "Maserati",
    "Bugatti",
    "McLaren",
    "Lexus",
    "Infiniti",
    "Acura",
    "Genesis",
    # Food & Beverages
    "Coca-Cola",
    "Pepsi",
    "Nestle",
    "Starbucks",
    "McDonald's",
    "KFC",
    "Subway",
    "Red Bull",
    "Heineken",
    "Budweiser",
    "Danone",
    "Kraft",
    "Kellogg's",
    "Lay's",
    "Mars",
    "Snickers",
    "Kit Kat",
    "Oreo",
    "Pringles",
    "Monster Energy",
    # Beauty & Personal Care
    "L'Oreal",
    "Maybelline",
    "MAC",
    "Estee Lauder",
    "Clinique",
    "Dove",
    "Nivea",
    "Garnier",
    "Pantene",
    "Head & Shoulders",
    "Gillette",
    "Old Spice",
    "Axe",
    "Olay",
    "Neutrogena",
    "Revlon",
    "Rimmel",
    "NYX",
    "Urban Decay",
    "Benefit",
    # Home & Furniture
    "IKEA",
    "Ashley Furniture",
    "La-Z-Boy",
    "Whirlpool",
    "Bosch",
    "Dyson",
    "Black+Decker",
    "KitchenAid",
    "Cuisinart",
    "OXO",
    "West Elm",
    "Pottery Barn",
    "Crate & Barrel",
    "CB2",
    "Room & Board",
    "Restoration Hardware",
    "Ethan Allen",
    "Williams Sonoma",
    "Le Creuset",
    "Tefal",
    # Sports & Outdoor
    "The North Face",
    "Patagonia",
    "Columbia",
    "Timberland",
    "New Balance",
    "ASICS",
    "Salomon",
    "Arc'teryx",
    "Oakley",
    "Ray-Ban",
    "Skechers",
    "Vans",
    "Converse",
    "Fila",
    "Brooks",
    "Hoka",
    "Merrell",
    "Keen",
    "Mammut",
    "Osprey",
    # Luxury & Watches
    "Rolex",
    "Omega",
    "Cartier",
    "Tissot",
    "Tag Heuer",
    "Fossil",
    "Casio",
    "Seiko",
    "Citizen",
    "Swatch",
]
