# Producer credentials
producer.username=producer
producer.password=producer-secret

# Consumer credentials
consumer.username=consumer
consumer.password=consumer-secret

# Client API credentials
client_api.username=client_api
client_api.password=client-api-secret

# Faust credentials
faust.username=faust
faust.password=faust-secret

# Analytics credentials
analytics.username=analytics
analytics.password=analytics-secret
