KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_producer="producer-secret"
  user_consumer="consumer-secret"
  user_client_api="client-api-secret"
  user_faust="faust-secret"
  user_analytics="analytics-secret";
};
